### ISSUE TITLE
无法识别到卡

### ISSUE THREAD

**Issue by wodianw** [KCORES/KCORES-FlexibleLOM-Adapter#6]
特定型号存在无法识别到卡
技嘉b360m-gamming
微星b360 b460
均无法识别，可能存在pcie插入检测

**Comment by alphaarea** [comment]
v1.1 已修复 PRSNT 连接
https://github.com/KCORES/KCORES-FlexibleLOM-Adapter/commit/cd2b0448e99b53122162201c7c03747a536e690a
