### ISSUE TITLE
沒看到gerber文件？

### ISSUE THREAD

**Issue by mlc130104** [KCORES/KCORES-FlexibleLOM-Adapter#7]
```
/Gerber/
The current version of the gerber file
当前版本的 gerber 生产文件
```

請問一下是收起了來嗎？

**Comment by alphaarea** [comment]
还没有发布Gerber文件，可以自己使用KiCAD导出

**Comment by alphaarea** [comment]
在 Release 中放入了 gerber 文件
[KCORES FlexibleLOM Adapter V1.0](https://github.com/KCORES/KCORES-FlexibleLOM-Adapter/releases/tag/v1.0)
